# Generated by Django 4.1.4 on 2023-01-05 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=75)),
                ('mensagem', models.TextField()),
                ('data', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reservaservico',
            name='id_pet',
        ),
        migrations.RemoveField(
            model_name='reservaservico',
            name='id_reponsavel',
        ),
        migrations.DeleteModel(
            name='CadastroPet',
        ),
        migrations.DeleteModel(
            name='ReservaServico',
        ),
        migrations.DeleteModel(
            name='Responsavel',
        ),
    ]
