# Generated by Django 4.1.4 on 2023-01-06 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_contato_remove_reservaservico_id_pet_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pet', models.CharField(max_length=50, verbose_name='Dia da Reserva')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('dia_reserva', models.DateField(max_length=14, verbose_name='Dia da Reserva')),
                ('observacoes', models.TextField(verbose_name='Observações')),
            ],
        ),
    ]
