# Generated by Django 4.1.4 on 2023-01-06 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_reserva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contato',
            options={'ordering': ['-data'], 'verbose_name': 'Formulário de Contato', 'verbose_name_plural': 'Formulários de Contatos'},
        ),
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-dia_reserva'], 'verbose_name': 'Reserva de Banho', 'verbose_name_plural': 'Reservas de Banhos'},
        ),
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateTimeField(auto_now=True, verbose_name='Dia de criação'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='nome_pet',
            field=models.CharField(max_length=50, verbose_name='Nome do Pet'),
        ),
    ]
