# Generated by Django 4.1.4 on 2023-01-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_reserva_dia_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='hora_banho',
            field=models.TimeField(default=1, verbose_name='Hora do Banho'),
            preserve_default=False,
        ),
    ]
