# Generated by Django 4.1.4 on 2023-01-06 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_reserva_hora_banho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='hora_banho',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia_reserva',
            field=models.DateTimeField(max_length=14, verbose_name='Dia e hora do Banho'),
        ),
    ]
