# Generated by Django 4.1.4 on 2023-01-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_reserva_hora_banho_alter_reserva_dia_reserva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data',
        ),
    ]
