# Generated by Django 4.1.4 on 2023-01-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_contato_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserva',
            name='dia_reserva',
            field=models.DateField(verbose_name='Dia do Banho'),
        ),
    ]
