# Generated by Django 4.1.4 on 2023-01-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_reserva_data_alter_reserva_dia_reserva'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data',
            field=models.DateTimeField(verbose_name='Data da reserva'),
        ),
    ]
