# Generated by Django 4.1.4 on 2023-01-06 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_alter_reserva_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
